### ISSUE TITLE
Play does not work. The parameters passed to the application had an invalid format.

### ISSUE THREAD

**Issue by COLABORATI** [fossfreedom/radio-browser#13]
First thank you very much for maintaining this application - it is sometimes a pain to do simple things with Ubuntu when it comes to standard multimedia features expected by everybody and little gems like this app are really important on a way to user acceptance, your efforts are great and I wish this would be part of the mainstream Ubuntu distro!

I installed the radio-browser plugin from your ppa - btw you should add the ppa install description from the linked askubuntu thread to the readme of this repository - it triggers some ambiguity if there are two different places of the seamingly same thing telling different stories about how to install. 

Ok, back to the bug - the first click on the Radio Browser immediately crashes Rhythmbox. However, a second try opens the Radio Browser GUI elements and allows to search for a radio station, what I did. 

Pressing the 'Play' button of the lower infobox generated by the search result then generates this error message: 

```
The parameters passed to the application had an invalid format. Please file a bug!

The parameters were:
--transient-for=81788939
gstreamer|1.0|rhythmbox|text/uri-list decoder|decoder-text/uri-list

```

Starting Rhythmbox from a terminal window I get some more output about a missing plugin: 

```
Rhythmbox-Message: Missing plugin: gstreamer|1.0|rhythmbox|text/uri-list decoder|decoder-text/uri-list
invalid commandline '['--transient-for=81788939', 'gstreamer|1.0|rhythmbox|text/uri-list decoder|decoder-text/uri-list']'
Rhythmbox-Message: Missing plugin installation failed: install-error
```

I believe to have all the gstreamer plugins installed that come with Ubuntu 14.04 - but there are simply too many gstreamer things generated by an `aptitude search gstreamer` so I am not clear about what exactly needs to be installed - if there is any missing dependency, then this should be handled by the installation procedure to avoid user frustrations. 

Pressing the 'Bookmark' button works, pressing the 'Record' button opens the recording GUI element, but nothing ever happens then. The console output indicates that there is another error: 

```
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/rhythmbox/plugins/radio-browser/record_process.py", line 202, in run
    line = line + char
TypeError: Can't convert 'bytes' object to str implicitly
```

It would be great to have these kind of standard things working flawlessly in Ubuntu, too, so your efforts are very appreciated! Thanks for your attention.
##

**Comment by fossfreedom** [comment]
Please can you have a look at the README and see if the current GIT version resolves the playback/record issue.
